# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'asdfsdf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for asdfsdf
	pod ‘Firebase/Core’
	pod ‘Firebase/Messaging’
	pod ‘Firebase/Database’
	pod ‘Firebase/Auth’
	pod ‘Firebase/Storage’
	pod ’Stripe’
    
  target 'asdfsdfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'asdfsdfUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
